language: cpp

before_install:
  - sudo apt-get install openmpi-bin libopenmpi-dev libnetcdf-dev netcdf-bin
  - sudo apt-get install cmake clang

install:
  - cmake . -DCMAKE_BUILD_TYPE=Debug
  - make

script:
  - ctest -V

env:
  -OMPI_CXX=clang++
  -OMPI_CXX=g++